import { RewardDefinition } from './reward-types';
import { REWARD_ACTIONS } from './actions';

export const REWARD_CONFIG: Record<string, RewardDefinition> = {
  ...REWARD_ACTIONS,

  guest_start: {
    coins: 100,
    totalPoints: 10,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Guest user starter reward',
  },
  register: {
    coins: 1000,
    totalPoints: 20,
    levelProgress: 20,
    once: true,
    enabled: true,
    safe: true,
    description: 'New user registration reward',
  },
  daily_login: {
    coins: 30,
    totalPoints: 10,
    levelProgress: 10,
    once: false,
    enabled: true,
    safe: true,
    description: 'Daily login reward',
  },
  daily_casino_checkin: {
    coins: 25,
    totalPoints: 5,
    levelProgress: 5,
    once: false,
    enabled: true,
    safe: true,
    description: 'Daily casino check-in reward',
  },
  profile_50_complete: {
    coins: 5,
    totalPoints: 20,
    levelProgress: 5,
    once: true,
    enabled: true,
    safe: true,
    description: 'Complete 50% of your profile',
  },
  profile_80_complete: {
    coins: 10,
    totalPoints: 40,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Complete 80% of your profile',
  },
  complete_profile: {
    coins: 20,
    totalPoints: 80,
    levelProgress: 20,
    once: true,
    enabled: true,
    safe: true,
    description: 'Complete your public profile page',
  },
  verify_email: {
    coins: 100,
    totalPoints: 15,
    levelProgress: 15,
    once: true,
    enabled: true,
    safe: true,
    description: 'Verify email address',
  },
  follow_casino: {
    coins: 10,
    totalPoints: 5,
    levelProgress: 5,
    once: false,
    enabled: true,
    safe: true,
    description: 'Follow a casino',
  },
  write_review: {
    coins: 50,
    totalPoints: 10,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Write a review',
  },
  share_casino: {
    coins: 20,
    totalPoints: 5,
    levelProgress: 5,
    once: false,
    enabled: true,
    safe: true,
    description: 'Share a casino',
  },
  add_favorite: {
    coins: 10,
    totalPoints: 5,
    levelProgress: 5,
    once: false,
    enabled: true,
    safe: true,
    description: 'Add a casino to favorites',
  },
  refer_friend: {
    coins: 200,
    totalPoints: 20,
    levelProgress: 20,
    once: false,
    enabled: true,
    safe: true,
    description: 'Refer a friend',
  },
  first_deposit: {
    coins: 500,
    totalPoints: 30,
    levelProgress: 30,
    once: true,
    enabled: true,
    safe: true,
    description: 'First deposit reward',
  },
  first_bet: {
    coins: 100,
    totalPoints: 15,
    levelProgress: 15,
    once: true,
    enabled: true,
    safe: true,
    description: 'First bet reward',
  },
  win_game: {
    coins: 150,
    totalPoints: 10,
    levelProgress: 10,
    once: false,
    enabled: true,
    safe: true,
    description: 'Win a game reward',
  },
  watch_tutorial: {
    coins: 20,
    totalPoints: 5,
    levelProgress: 5,
    once: true,
    enabled: true,
    safe: true,
    description: 'Watch tutorial content',
  },
  play_5_games: {
    coins: 30,
    totalPoints: 10,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Play 5 games',
  },
  play_10_games: {
    coins: 60,
    totalPoints: 15,
    levelProgress: 15,
    once: true,
    enabled: true,
    safe: true,
    description: 'Play 10 games',
  },
  complete_daily_mission: {
    coins: 80,
    totalPoints: 20,
    levelProgress: 20,
    once: true,
    enabled: true,
    safe: true,
    description: 'Complete a daily mission',
  },
  complete_weekly_mission: {
    coins: 200,
    totalPoints: 50,
    levelProgress: 50,
    once: true,
    enabled: true,
    safe: true,
    description: 'Complete a weekly mission',
  },
  complete_level: {
    coins: 100,
    totalPoints: 20,
    levelProgress: 20,
    once: true,
    enabled: true,
    safe: true,
    description: 'Complete a level',
  },
  login_7_day_streak: {
    coins: 300,
    totalPoints: 50,
    levelProgress: 50,
    once: true,
    enabled: true,
    safe: true,
    description: 'Login 7-day streak reward',
  },
  claim_daily_streak: {
    coins: 40,
    totalPoints: 10,
    levelProgress: 10,
    once: false,
    enabled: true,
    safe: true,
    description: 'Claim daily streak reward',
  },
  review_verified: {
    coins: 60,
    totalPoints: 10,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Verified review reward',
  },
  add_payment_method: {
    coins: 20,
    totalPoints: 10,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Add payment method',
  },
  follow_newsletter: {
    coins: 30,
    totalPoints: 10,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Subscribe to newsletter',
  },
  add_avatar: {
    coins: 10,
    totalPoints: 5,
    levelProgress: 5,
    once: true,
    enabled: true,
    safe: true,
    description: 'Add avatar/profile image',
  },
  connect_social: {
    coins: 20,
    totalPoints: 10,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Connect a social account',
  },
  submit_feedback: {
    coins: 30,
    totalPoints: 10,
    levelProgress: 10,
    once: true,
    enabled: true,
    safe: true,
    description: 'Submit feedback',
  },
  watch_promo: {
    coins: 15,
    totalPoints: 5,
    levelProgress: 5,
    once: false,
    enabled: true,
    safe: true,
    description: 'Watch a promo or announcement',
  },
  complete_survey: {
    coins: 80,
    totalPoints: 20,
    levelProgress: 20,
    once: true,
    enabled: true,
    safe: true,
    description: 'Complete a survey',
  },
  share_referral: {
    coins: 100,
    totalPoints: 15,
    levelProgress: 15,
    once: false,
    enabled: true,
    safe: true,
    description: 'Share a referral link',
  },
  play_new_game: {
    coins: 40,
    totalPoints: 10,
    levelProgress: 10,
    once: false,
    enabled: true,
    safe: true,
    description: 'Play a new game',
  },
  join_tournament: {
    coins: 100,
    totalPoints: 20,
    levelProgress: 20,
    once: true,
    enabled: true,
    safe: true,
    description: 'Join a tournament',
  },
  win_tournament: {
    coins: 500,
    totalPoints: 60,
    levelProgress: 60,
    once: true,
    enabled: true,
    safe: true,
    description: 'Win a tournament',
  },
  complete_quest: {
    coins: 120,
    totalPoints: 25,
    levelProgress: 25,
    once: true,
    enabled: true,
    safe: true,
    description: 'Complete a quest',
  },
  click_google_ads: {
    coins: 0,
    totalPoints: 0,
    levelProgress: 0,
    once: false,
    enabled: false,
    safe: false,
    description: 'Disabled high-risk Google Ads click reward',
    antiAbuse: 'Never reward users for ads',
  },
  click_affiliate_links_directly: {
    coins: 0,
    totalPoints: 0,
    levelProgress: 0,
    once: false,
    enabled: false,
    safe: false,
    description: 'Disabled high-risk affiliate link reward',
    antiAbuse: 'Avoid monetized clicks for reward',
  },
  forced_popups_redirects: {
    coins: 0,
    totalPoints: 0,
    levelProgress: 0,
    once: false,
    enabled: false,
    safe: false,
    description: 'Disabled unsafe popup/redirect reward',
    antiAbuse: 'Never reward forced redirects',
  },
  auto_click_scripts_bots: {
    coins: 0,
    totalPoints: 0,
    levelProgress: 0,
    once: false,
    enabled: false,
    safe: false,
    description: 'Disabled unsafe bot automation reward',
    antiAbuse: 'Do not reward scripted or bot actions',
  },
};
