import { CoreActionDetail } from './types';

export const CORE_ACTIONS: CoreActionDetail[] = [
  {
    action: 'Visit homepage',
    xp: 1,
    coins: 0,
    cooldown: '10 min',
    dailyLimit: '20',
    antiAbuseRule: 'Ignore repeat same session',
    details: 'Only counted once per session refresh cycle',
    notes: '✅ Safe',
  },
  {
    action: 'Visit casino page',
    xp: 2,
    coins: 0,
    cooldown: '5 min',
    dailyLimit: '30',
    antiAbuseRule: 'Unique casino only',
    details: 'Visiting different casinos increases XP faster',
    notes: '✅ Safe',
  },
  {
    action: 'Click affiliate link',
    xp: 5,
    coins: 1,
    cooldown: '10 min',
    dailyLimit: '15',
    antiAbuseRule: 'Must redirect external',
    details: 'Reward only if user stays >10s on partner site',
    notes: '⚠️ Risky — avoid for Google Ads',
  },
  {
    action: 'Stay 30 seconds',
    xp: 2,
    coins: 0,
    cooldown: 'per session',
    dailyLimit: '20',
    antiAbuseRule: 'Real time tracking',
    details: 'Tab must be active and visible',
    notes: '✅ Safe',
  },
  {
    action: 'Stay 2 minutes',
    xp: 5,
    coins: 1,
    cooldown: 'per session',
    dailyLimit: '10',
    antiAbuseRule: 'Active tab only',
    details: 'Bonus stacks with 30s reward',
    notes: '✅ Safe',
  },
  {
    action: 'Stay 5 minutes',
    xp: 8,
    coins: 2,
    cooldown: 'per session',
    dailyLimit: '5',
    antiAbuseRule: 'Scroll required',
    details: 'Requires at least 30% scroll activity',
    notes: '✅ Safe',
  },
  {
    action: 'Scroll 50% page',
    xp: 2,
    coins: 0,
    cooldown: 'per page',
    dailyLimit: '20',
    antiAbuseRule: 'Unique page',
    details: 'Encourages content consumption',
    notes: '✅ Safe',
  },
  {
    action: 'Scroll 90% page',
    xp: 4,
    coins: 1,
    cooldown: 'per page',
    dailyLimit: '10',
    antiAbuseRule: 'No bot scroll',
    details: 'High engagement reward',
    notes: '✅ Safe',
  },
  {
    action: 'Click bonus',
    xp: 3,
    coins: 1,
    cooldown: '5 min',
    dailyLimit: '20',
    antiAbuseRule: 'Unique bonus',
    details: 'Only first click per bonus counts',
    notes: '✅ Safe',
  },
  {
    action: 'Claim bonus',
    xp: 6,
    coins: 2,
    cooldown: '30 min',
    dailyLimit: '10',
    antiAbuseRule: 'Must be valid bonus',
    details: 'Bonus must be active and valid',
    notes: '✅ Safe',
  },
];
