import { LevelSystemTier } from './types';

export const LEVEL_SYSTEM: LevelSystemTier[] = [
  {
    level: 1,
    pointsRequired: 100,
    totalXp: 100,
    rewardCoins: 5,
    details: 'Entry level, fast onboarding',
    notes: '✅ Safe',
  },
  {
    level: 2,
    pointsRequired: 250,
    totalXp: 350,
    rewardCoins: 6,
    details: 'Slightly harder progression',
    notes: '✅ Safe',
  },
  {
    level: 3,
    pointsRequired: 500,
    totalXp: 850,
    rewardCoins: 8,
    details: 'Engagement starts here',
    notes: '✅ Safe',
  },
  {
    level: 4,
    pointsRequired: 900,
    totalXp: 1750,
    rewardCoins: 10,
    details: 'Users become regular',
    notes: '✅ Safe',
  },
  {
    level: 5,
    pointsRequired: 1500,
    totalXp: 3250,
    rewardCoins: 12,
    details: 'Strong retention phase',
    notes: '✅ Safe',
  },
  {
    level: 6,
    pointsRequired: 2500,
    totalXp: 5750,
    rewardCoins: 15,
    details: 'Mid-level grind begins',
    notes: '✅ Safe',
  },
  {
    level: 7,
    pointsRequired: 4000,
    totalXp: 9750,
    rewardCoins: 18,
    details: 'Loyal users only',
    notes: '✅ Safe',
  },
  {
    level: 8,
    pointsRequired: 6500,
    totalXp: 16250,
    rewardCoins: 22,
    details: 'High engagement users',
    notes: '✅ Safe',
  },
  {
    level: 9,
    pointsRequired: 10000,
    totalXp: 26250,
    rewardCoins: 30,
    details: 'Power users',
    notes: '✅ Safe',
  },
  {
    level: 10,
    pointsRequired: 15000,
    totalXp: 41250,
    rewardCoins: 40,
    details: 'VIP entry point',
    notes: '✅ Safe',
  },
];
